### ISSUE TITLE
Not reading wol_config.ini file.

### ISSUE THREAD

**Issue by vdbpeter** [bentasker/Wake-On-Lan-Python#7]
Hi guys- cute script- thanks!
Just pointing out that in your code in line 66 you're referencing 	`Config.read(mydir+"/.wol_config.ini")`  but wol_config.ini should **not** be a hidden file.

Cheers

**Comment by bentasker** [comment]
It was thrown together ages ago for this - https://www.bentasker.co.uk/documentation/linux/258-usurping-the-bthomehub-with-a-raspberry-pi-part-three-routing-remote-administration-and-utilities 

The intention, originally had been to move the config file to the users home dir (which is why it's a hidden file), although of course really by today's standards it should go into `~/.config` or somewhere.

Feel free to open a pull updating the location

**Comment by jNullj** [comment]
I don't mind making a pull request. I suggest using the [XDG specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Which state:

```
$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

A user-specific version of the configuration file may be created in $XDG_CONFIG_HOME/subdir/filename, taking into account the default value for $XDG_CONFIG_HOME if $XDG_CONFIG_HOME is not set.
```

I think a proper subdir name would be `bentasker.Wake-On-Lan-Python`. Let me know if that sounds good and i will make the changes.

**Comment by bentasker** [comment]
Sounds good to me, please go for it.

I've a busy weekend, so likely won't merge until in the week
